security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_CREDENTIALS_CREATE
            - ROLE_PROJECT_CREATE
            - ROLE_PROJECT_GROUP_CREATE
            - ROLE_SERVER_CREATE
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        app:
            pattern: ^/
            custom_authenticators:
                - App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                name: REMEMBERME
                always_remember_me: true
                lifetime: 2592000
                path: /
                secret: '%kernel.secret%'

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/.*, roles: IS_AUTHENTICATED_REMEMBERED }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
