sonata_admin:
    title: 'Manager'
    search: false
    show_mosaic_button: false
    options:
        form_type: horizontal
    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    dashboard:
        groups:
            project:
                on_top: true
                label: admin.project
                label_catalogue: messages
                icon: '<i class="fa fa-code"></i>'
                items:
                    - admin.project
            server:
                on_top: true
                label: admin.server
                label_catalogue: messages
                icon: '<i class="fa fa-server"></i>'
                items:
                    - admin.server
            customer:
                on_top: true
                label: admin.customer
                label_catalogue: messages
                icon: '<i class="fa fa-address-book"></i>'
                items:
                    - admin.customer
            credentials:
                on_top: true
                label: admin.credentials
                label_catalogue: messages
                icon: '<i class="fa fa-key"></i>'
                items:
                    - admin.credentials
            settings:
                keep_open: true
                label: admin.group.settings
                label_catalogue: messages
                icon: '<i class="fa fa-wrench"></i>'
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        layout: 'app/layout.html.twig'
        user_block: 'app/user_block.html.twig'
    assets:
        extra_javascripts:
            - bundles/sortablebehavior/js/init.js

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_doctrine_orm_admin:
    templates:
        form: ['app/form/form_admin_fields.html.twig']
