vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix: /uploads/project
            upload_destination: '%kernel.project_dir%/public/uploads/project'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
