services:
    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: settings, label: admin.user }
        calls:
            - [addChild, ['@admin.ssh_key', 'user']]
            - [setPasswordEncoder, ['@security.password_encoder']]

    admin.ssh_key:
        class: App\Admin\SshKeyAdmin
        arguments: [~, App\Entity\CryptographicKey, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: settings, label: admin.ssh_key }

    admin.project:
        class: App\Admin\ProjectAdmin
        arguments: [~, App\Entity\Project, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: project, label: admin.project }

    admin.project_type:
        class: App\Admin\ProjectTypeAdmin
        arguments: [~, App\Entity\ProjectType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: settings, label: admin.project_type }

    admin.project_environment:
        class: App\Admin\ProjectEnvironmentAdmin
        arguments: [~, App\Entity\ProjectEnvironment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: project, label: admin.project_environment }

    admin.server:
        class: App\Admin\ServerAdmin
        arguments: [~, App\Entity\Server, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: server, label: admin.server }

    admin.server_user:
        class: App\Admin\ServerUserAdmin
        arguments: [~, App\Entity\ServerUser, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: server, label: admin.server_user }

    admin.customer:
        class: App\Admin\CustomerAdmin
        arguments: [~, App\Entity\Customer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: customer, label: admin.customer }
        calls:
            - [addChild, ['@admin.customer_contact', 'customer']]

    admin.customer_contact:
        class: App\Admin\CustomerContactAdmin
        arguments: [~, App\Entity\CustomerContact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: customer, label: admin.customer_contact }

    admin.credentials:
        class: App\Admin\CredentialsAdmin
        arguments: [~, App\Entity\Credentials, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: credentials, label: admin.credentials }
