parameters:
    locale: fr

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $locale: '%locale%'
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Action\:
        resource: '../src/Action'
        tags: [ 'controller.service_arguments' ]

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Menu\AdminMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: create, alias: admin }

    App\Menu\UserSettingsMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: create, alias: user_settings }

    App\Menu\ProjectGroupMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: create, alias: project_group }

    App\Menu\ProjectMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: create, alias: project }

    App\Menu\ServerMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: create, alias: server }

    _instanceof:
        App\Routing\EntityUrlGeneratorInterface:
            tags: [ 'app.entity_url_generator' ]
