services:
    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: admin.user, label_translator_strategy: sonata.admin.label.strategy.underscore }
        calls:
            - [setPasswordEncoder, ['@security.password_encoder']]
